In [77]:
import duckdb

In [78]:
con = duckdb.connect(
    database='./data_duckdb.db',
    read_only=False
)

In [79]:
con.execute(
    '''
    SELECT *
    FROM products
    '''
).fetchdf()

      id product_name id_category  id_supplier  value_price
0  10002      MARTELO        BT50          100       1500.0
1  10003        PREGO        BT10          100         60.0
2  10005      MACHADO        BT50          100        100.0
3  10001     PARAFUSO        BT10          100        100.0
4  10004        SERRA        BT50          100        200.0

In [80]:
df = con.execute(
    '''
    SELECT *
    FROM products
    '''
).fetchdf()

df

      id product_name id_category  id_supplier  value_price
0  10002      MARTELO        BT50          100       1500.0
1  10003        PREGO        BT10          100         60.0
2  10005      MACHADO        BT50          100        100.0
3  10001     PARAFUSO        BT10          100        100.0
4  10004        SERRA        BT50          100        200.0

In [81]:
df2 = df.drop(columns=['id_category', 'id_supplier'])

In [82]:
df2

      id product_name  value_price
0  10002      MARTELO       1500.0
1  10003        PREGO         60.0
2  10005      MACHADO        100.0
3  10001     PARAFUSO        100.0
4  10004        SERRA        200.0

In [83]:
con.execute(
    '''
    CREATE TABLE IF NOT EXISTS dim_products (
        product_id BIGINT,
        product_name TEXT,
        product_value FLOAT
    )
    '''
)

In [84]:
df_dim = con.execute(
    '''
    SELECT *
    FROM dim_products
    '''
).fetchdf()

df_dim

   PRODUCT_ID PRODUCT_NAME  PRODUCUT_VALUE
0       10002      MARTELO          1500.0
1       10003        PREGO            60.0
2       10005      MACHADO           100.0
3       10001     PARAFUSO           100.0
4       10004        SERRA           200.0
5       10002      MARTELO          1500.0
6       10003        PREGO            60.0
7       10005      MACHADO           100.0
8       10001     PARAFUSO           100.0
9       10004        SERRA           200.0

In [85]:
con.execute(
    '''
    DROP TABLE dim_products
    '''
)

In [86]:
con.execute(
    '''
    SELECT *
    FROM dim_products
    '''
).fetchdf()

CatalogException: Catalog Error: Table with name dim_products does not exist!
Did you mean "products"?

LINE 3:     FROM dim_products
                 ^

In [87]:
con.execute(
    '''
    CREATE TABLE IF NOT EXISTS dim_products (
        PRODUCT_ID BIGINT,
        PRODUCT_NAME TEXT,
        PRODUCT_VALUE FLOAT
    )
    '''
)

In [88]:
con.execute(
    '''
    SELECT *
    FROM dim_products
    '''
).fetchdf()

Empty DataFrame
Columns: [PRODUCT_ID, PRODUCT_NAME, PRODUCT_VALUE]
Index: []

In [89]:
df2

      id product_name  value_price
0  10002      MARTELO       1500.0
1  10003        PREGO         60.0
2  10005      MACHADO        100.0
3  10001     PARAFUSO        100.0
4  10004        SERRA        200.0

In [90]:
con.execute(
    '''
    INSERT INTO dim_products
    SELECT *
    FROM df2
    '''
)

In [91]:
df_dim = con.execute(
    '''
    SELECT *
    FROM dim_products
    '''
).fetchdf()

df_dim

   PRODUCT_ID PRODUCT_NAME  PRODUCT_VALUE
0       10002      MARTELO         1500.0
1       10003        PREGO           60.0
2       10005      MACHADO          100.0
3       10001     PARAFUSO          100.0
4       10004        SERRA          200.0

In [92]:
con.close()