In [16]:
import duckdb

In [17]:
con = duckdb.connect(
    database='data_duckdb.db',
    read_only=False
)

In [18]:
con.execute(
    '''
    SELECT *
    FROM bronze_z0019
    '''
)

In [19]:
df = con.execute(
    '''
    SELECT *
    FROM bronze_z0019
    '''
).fetchdf()

df

   NATBR     MAKTX WERKS MAINS LABST    file_name                date_intake
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2025-06-24 00:52:35.578921
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2025-06-24 00:52:35.578921
2  10003     PREGO  BT10   100    50  z0019_1.csv 2025-06-24 00:52:35.578921
3  10004     SERRA  BT50   100   200  z0019_2.csv 2025-06-24 00:54:00.699234
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2025-06-24 00:54:00.699234
5  10003     PREGO  BT10   100    60  z0019_2.csv 2025-06-24 00:54:00.699234

In [20]:
df = con.execute(
    '''
    SELECT *
    FROM bronze_z0019
    WHERE date_intake >= '2025-06-24'
    '''
).fetchdf()

df

   NATBR     MAKTX WERKS MAINS LABST    file_name                date_intake
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2025-06-24 00:52:35.578921
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2025-06-24 00:52:35.578921
2  10003     PREGO  BT10   100    50  z0019_1.csv 2025-06-24 00:52:35.578921
3  10004     SERRA  BT50   100   200  z0019_2.csv 2025-06-24 00:54:00.699234
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2025-06-24 00:54:00.699234
5  10003     PREGO  BT10   100    60  z0019_2.csv 2025-06-24 00:54:00.699234

In [21]:
df = con.execute(
    '''
    SELECT *, ROW_NUMBER() OVER (PARTITION BY NATBR ORDER BY date_intake DESC) AS row
    FROM bronze_z0019
    WHERE date_intake >= '2025-06-24'
    '''
).fetchdf()

df

,NATBR,MAKTX,WERKS,MAINS,LABST,file_name,date_intake,row
0,10004,SERRA,BT50,100,200,z0019_2.csv,2025-06-24 00:54:00.699234,1
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2025-06-24 00:52:35.578921,1
2,10003,PREGO,BT10,100,60,z0019_2.csv,2025-06-24 00:54:00.699234,1
3,10003,PREGO,BT10,100,50,z0019_1.csv,2025-06-24 00:52:35.578921,2
4,10005,MACHADO,BT50,100,100,z0019_2.csv,2025-06-24 00:54:00.699234,1
5,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-06-24 00:52:35.578921,1

In [22]:
df = con.execute(
    '''
    SELECT *
    FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY NATBR ORDER BY date_intake DESC) AS row
        FROM bronze_z0019
        WHERE date_intake >= '2025-06-24'
    )
    '''
).fetchdf()

df

,NATBR,MAKTX,WERKS,MAINS,LABST,file_name,date_intake,row
0,10004,SERRA,BT50,100,200,z0019_2.csv,2025-06-24 00:54:00.699234,1
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2025-06-24 00:52:35.578921,1
2,10003,PREGO,BT10,100,60,z0019_2.csv,2025-06-24 00:54:00.699234,1
3,10003,PREGO,BT10,100,50,z0019_1.csv,2025-06-24 00:52:35.578921,2
4,10005,MACHADO,BT50,100,100,z0019_2.csv,2025-06-24 00:54:00.699234,1
5,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-06-24 00:52:35.578921,1

In [23]:
df = con.execute(
    '''
    SELECT *
    FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY NATBR ORDER BY date_intake DESC) AS row
        FROM bronze_z0019
        WHERE date_intake >= '2025-06-24'
    ) WHERE row = 1
    '''
).fetchdf()

df

,NATBR,MAKTX,WERKS,MAINS,LABST,file_name,date_intake,row
0,10004,SERRA,BT50,100,200,z0019_2.csv,2025-06-24 00:54:00.699234,1
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2025-06-24 00:52:35.578921,1
2,10003,PREGO,BT10,100,60,z0019_2.csv,2025-06-24 00:54:00.699234,1
3,10005,MACHADO,BT50,100,100,z0019_2.csv,2025-06-24 00:54:00.699234,1
4,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-06-24 00:52:35.578921,1

In [24]:
df

,NATBR,MAKTX,WERKS,MAINS,LABST,file_name,date_intake,row
0,10004,SERRA,BT50,100,200,z0019_2.csv,2025-06-24 00:54:00.699234,1
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2025-06-24 00:52:35.578921,1
2,10003,PREGO,BT10,100,60,z0019_2.csv,2025-06-24 00:54:00.699234,1
3,10005,MACHADO,BT50,100,100,z0019_2.csv,2025-06-24 00:54:00.699234,1
4,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-06-24 00:52:35.578921,1

In [25]:
df_final = df.drop(columns=['file_name', 'date_intake', 'row'])

df_final

   NATBR     MAKTX WERKS MAINS LABST
0  10004     SERRA  BT50   100   200
1  10002   MARTELO  BT50   100  1500
2  10003     PREGO  BT10   100    60
3  10005   MACHADO  BT50   100   100
4  10001  PARAFUSO  BT10   100   100

In [26]:
df_final.rename(columns={'NATBR':'id'})

      id     MAKTX WERKS MAINS LABST
0  10004     SERRA  BT50   100   200
1  10002   MARTELO  BT50   100  1500
2  10003     PREGO  BT10   100    60
3  10005   MACHADO  BT50   100   100
4  10001  PARAFUSO  BT10   100   100

In [27]:
df_final = df_final.rename(columns={'NATBR':'id',            # identificador
                                    'MAKTX': 'product_name', # nome do produto 
                                    'WERKS': 'id_category',     # categória
                                    'MAINS': 'id_supplier',     # fornecedor
                                    'LABST': 'value_price'})       # preço

df_final

      id product_name id_category id_supplier value_price
0  10004        SERRA        BT50         100         200
1  10002      MARTELO        BT50         100        1500
2  10003        PREGO        BT10         100          60
3  10005      MACHADO        BT50         100         100
4  10001     PARAFUSO        BT10         100         100