In [1]:
import duckdb

In [2]:
con = duckdb.connect(
    database='data_duckdb.db',
    read_only=False
)

In [3]:
con.execute(
    '''
    SELECT *
    FROM bronze_z0019
    '''
)

In [4]:
df = con.execute(
    '''
    SELECT *
    FROM bronze_z0019
    '''
).fetchdf()

df

   NATBR     MAKTX WERKS MAINS LABST    file_name                date_intake
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2025-06-24 00:52:35.578921
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2025-06-24 00:52:35.578921
2  10003     PREGO  BT10   100    50  z0019_1.csv 2025-06-24 00:52:35.578921
3  10004     SERRA  BT50   100   200  z0019_2.csv 2025-06-24 00:54:00.699234
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2025-06-24 00:54:00.699234
5  10003     PREGO  BT10   100    60  z0019_2.csv 2025-06-24 00:54:00.699234

In [5]:
df = con.execute(
    '''
    SELECT *
    FROM bronze_z0019
    WHERE date_intake >= '2025-06-24'
    '''
).fetchdf()

df

   NATBR     MAKTX WERKS MAINS LABST    file_name                date_intake
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2025-06-24 00:52:35.578921
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2025-06-24 00:52:35.578921
2  10003     PREGO  BT10   100    50  z0019_1.csv 2025-06-24 00:52:35.578921
3  10004     SERRA  BT50   100   200  z0019_2.csv 2025-06-24 00:54:00.699234
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2025-06-24 00:54:00.699234
5  10003     PREGO  BT10   100    60  z0019_2.csv 2025-06-24 00:54:00.699234

In [6]:
df = con.execute(
    '''
    SELECT *, ROW_NUMBER() OVER (PARTITION BY NATBR ORDER BY date_intake DESC) AS row
    FROM bronze_z0019
    WHERE date_intake >= '2025-06-24'
    '''
).fetchdf()

df

,NATBR,MAKTX,WERKS,MAINS,LABST,file_name,date_intake,row
0,10004,SERRA,BT50,100,200,z0019_2.csv,2025-06-24 00:54:00.699234,1
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2025-06-24 00:52:35.578921,1
2,10005,MACHADO,BT50,100,100,z0019_2.csv,2025-06-24 00:54:00.699234,1
3,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-06-24 00:52:35.578921,1
4,10003,PREGO,BT10,100,60,z0019_2.csv,2025-06-24 00:54:00.699234,1
5,10003,PREGO,BT10,100,50,z0019_1.csv,2025-06-24 00:52:35.578921,2

In [7]:
df = con.execute(
    '''
    SELECT *
    FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY NATBR ORDER BY date_intake DESC) AS row
        FROM bronze_z0019
        WHERE date_intake >= '2025-06-24'
    )
    '''
).fetchdf()

df

,NATBR,MAKTX,WERKS,MAINS,LABST,file_name,date_intake,row
0,10004,SERRA,BT50,100,200,z0019_2.csv,2025-06-24 00:54:00.699234,1
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2025-06-24 00:52:35.578921,1
2,10003,PREGO,BT10,100,60,z0019_2.csv,2025-06-24 00:54:00.699234,1
3,10003,PREGO,BT10,100,50,z0019_1.csv,2025-06-24 00:52:35.578921,2
4,10005,MACHADO,BT50,100,100,z0019_2.csv,2025-06-24 00:54:00.699234,1
5,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-06-24 00:52:35.578921,1

In [8]:
df = con.execute(
    '''
    SELECT *
    FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY NATBR ORDER BY date_intake DESC) AS row
        FROM bronze_z0019
        WHERE date_intake >= '2025-06-24'
    ) WHERE row = 1
    '''
).fetchdf()

df

,NATBR,MAKTX,WERKS,MAINS,LABST,file_name,date_intake,row
0,10004,SERRA,BT50,100,200,z0019_2.csv,2025-06-24 00:54:00.699234,1
1,10003,PREGO,BT10,100,60,z0019_2.csv,2025-06-24 00:54:00.699234,1
2,10005,MACHADO,BT50,100,100,z0019_2.csv,2025-06-24 00:54:00.699234,1
3,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-06-24 00:52:35.578921,1
4,10002,MARTELO,BT50,100,1500,z0019_1.csv,2025-06-24 00:52:35.578921,1

In [9]:
df

,NATBR,MAKTX,WERKS,MAINS,LABST,file_name,date_intake,row
0,10004,SERRA,BT50,100,200,z0019_2.csv,2025-06-24 00:54:00.699234,1
1,10003,PREGO,BT10,100,60,z0019_2.csv,2025-06-24 00:54:00.699234,1
2,10005,MACHADO,BT50,100,100,z0019_2.csv,2025-06-24 00:54:00.699234,1
3,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-06-24 00:52:35.578921,1
4,10002,MARTELO,BT50,100,1500,z0019_1.csv,2025-06-24 00:52:35.578921,1

In [10]:
df_final = df.drop(columns=['file_name', 'date_intake', 'row'])

df_final

   NATBR     MAKTX WERKS MAINS LABST
0  10004     SERRA  BT50   100   200
1  10003     PREGO  BT10   100    60
2  10005   MACHADO  BT50   100   100
3  10001  PARAFUSO  BT10   100   100
4  10002   MARTELO  BT50   100  1500

In [11]:
df_final.rename(columns={'NATBR':'id'})

      id     MAKTX WERKS MAINS LABST
0  10004     SERRA  BT50   100   200
1  10003     PREGO  BT10   100    60
2  10005   MACHADO  BT50   100   100
3  10001  PARAFUSO  BT10   100   100
4  10002   MARTELO  BT50   100  1500

In [12]:
df_final = df_final.rename(columns={'NATBR':'id',            # identificador
                                    'MAKTX': 'product_name', # nome do produto 
                                    'WERKS': 'id_category',     # categória
                                    'MAINS': 'id_supplier',     # fornecedor
                                    'LABST': 'value_price'})       # preço

df_final

      id product_name id_category id_supplier value_price
0  10004        SERRA        BT50         100         200
1  10003        PREGO        BT10         100          60
2  10005      MACHADO        BT50         100         100
3  10001     PARAFUSO        BT10         100         100
4  10002      MARTELO        BT50         100        1500

In [13]:
df_final.dtypes

id              object
product_name    object
id_category     object
id_supplier     object
value_price     object
dtype: object

In [14]:
df2 = df_final.copy()

df2

      id product_name id_category id_supplier value_price
0  10004        SERRA        BT50         100         200
1  10003        PREGO        BT10         100          60
2  10005      MACHADO        BT50         100         100
3  10001     PARAFUSO        BT10         100         100
4  10002      MARTELO        BT50         100        1500

In [15]:
df2 = df2.astype(
    {
        'id': 'int32',
        'product_name': 'string',
        'id_category': 'string',
        'id_supplier': 'int32',
        'value_price': 'float32'
    }
)

In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            5 non-null      int32
 1   product_name  5 non-null      string
 2   id_category   5 non-null      string
 3   id_supplier   5 non-null      int32
 4   value_price   5 non-null      float32
dtypes: float32(1), int32(2), string(2)
memory usage: 272.0 bytes

In [17]:
df2.dtypes

id                       int32
product_name    string[python]
id_category     string[python]
id_supplier              int32
value_price            float32
dtype: object

In [18]:
df2 = df2.astype(
    {
        'id': int,
        'product_name': str,
        'id_category': str,
        'id_supplier': int,
        'value_price': float
    }
)

In [19]:
df2.dtypes

id                int64
product_name     object
id_category      object
id_supplier       int64
value_price     float64
dtype: object

In [20]:
con.execute(
    '''
    CREATE TABLE IF NOT EXISTS products (
        id BIGINT,
        product_name TEXT,
        id_category TEXT,
        id_supplier BIGINT,
        value_price FLOAT
    )
    '''
)

In [21]:
df2

      id product_name id_category  id_supplier  value_price
0  10004        SERRA        BT50          100        200.0
1  10003        PREGO        BT10          100         60.0
2  10005      MACHADO        BT50          100        100.0
3  10001     PARAFUSO        BT10          100        100.0
4  10002      MARTELO        BT50          100       1500.0

In [22]:
df_result = con.execute(
    '''
    SELECT *
    FROM products
    '''
).fetchdf()

df_result

Empty DataFrame
Columns: [id, product_name, id_category, id_supplier, value_price]
Index: []

In [23]:
con.execute(
    '''
    INSERT INTO products
    SELECT *
    FROM df2
    '''
)